### PR TITLE
ddc_dumpload.c: portable format string for time_t (fixes build on x32)

### PR DESCRIPTION
**Pull request by jpalus**

### CODE REVIEW

**Comment by rockowitz** [comment]
Jan,

Thanks for the pull request.  The more I look into time_t the uglier it 
gets.   In C11 it becomes a real number.

The TIME_MILLIS field in the dumpload data file turned out not to be of 
use, and is ignored on input.  I'm inclined just not output it and avoid 
the whole issue of formatting time_t.

I'm curious though.  Can you describe the system on which you hit this 
problem?

Sanford

**Comment by jpalus** [comment]
Hi,

it's on [x32 ABI](https://en.wikipedia.org/wiki/X32_ABI) where %ld refers to 32bit value (long int), but time_t is 64bit (long long int). You can check exact build failure [here](http://buildlogs.pld-linux.org//index.php?dist=th&arch=x32&ok=0&ns=&cnt=50&off=0&name=ddcutil&id=efc45612-3d03-4c21-a77e-860c0fd5c5cc&action=text) (note that the URL will be valid only for few days).

**Comment by rockowitz** [comment]
Thanks.  I hadn't given thought to x32.  Of the cross-platform sites 
where ddcutil is built (Debian, OBS, COPR) only Debian has an x32 
option, and that is marked unofficial.

Sanford

**Comment by rockowitz** [comment]
The issue addressed by this pull request was instead resolved by a change to the ***dumpvcp*** command in **ddcutil** release 0.9.4.   The TIMESTAMP_MILLIS field has been eliminated.

**Pull request closed without merging**
