### PR TITLE
Fix spelling of 'Finnish'

### PR DESCRIPTION
**Pull request by SimonAlling**

### CODE REVIEW

**Comment by rockowitz** [comment]
Thank you for catching this.  Fix applied.

**Comment by SimonAlling** [comment]
> Thank you for catching this.

You're welcome!

> Fix applied.

Since I'm not familiar with the collaboration workflow in this repo and since the PR is still open, may I ask what you mean by this? :slightly_smiling_face:

**Comment by rockowitz** [comment]
Patches are rare, generally trivial, and sometimes not quite right.  
It's simpler for me to make the changes in my local copy rather than 
merge.  That may change if the frequency of patches changes, but for now 
that's what it is. You'll see that the Finnish fix is in branch 
0.9.9-dev.   I neglected to close the PR.

Sanford

**Comment by SimonAlling** [comment]
Oh. For the future, I'd like to suggest merging PRs instead of closing them. That way, PR authors are credited as co-authors, and it's easier for them/us and others to track their/our work on GitHub.

It was also not easy (and certainly won't be in a few days, weeks, months) to find [the commit you made on my behalf](https://github.com/rockowitz/ddcutil/commit/4c06d972d73e87f1216ea9f4314d0697a2485237), since its title on GitHub is just `vcp_feature_codes.c:` and doesn't mention anything about the actual fix. Why is that? By the way, the commit log is quite hard to read overall, so I think there would be great value in adopting another commit message style:

```console
$ git log --oneline
a9b4a203 (HEAD -> master) dyn_feature_codes.c/h: - dyn_format_nontable_feature_detail_dfm(), dyn_format_table_feature_detail_dfm():   - remove version spec from parameter list, get it out of Display_Feature_Metatdata parm   - old code just commented out, cleanup left for future  - dyn_format_feature_detal_dfm():    reflect above changes
e5146003 api_feature_access.c: - ddca_format_any_vcp_value_by_dref, ddca_format_non_table_vcp_value(), ddca_format_no_table_vcp_value_by_dref():   - eliminate assert() that return code = 0 iff a formatted value is returned   - in fact, if return code != 0, tan error message string is returned
7315467d api_feature_access_internal: - ddca_format_table_vcp_value():   - add documentation
9528079b dyn_feature_codes.c: - set global TRACE_GROUP for the file to DDCA_TRC_UDF - dyn_feature_format_detail_sl_lookup():   - convert DBGMSF() to DBGTRC() - dyn_format_feature_detail_dfm():   - convert DBGMSF() to DBGTRC()   - add additional tracing - dyn_format_feature_detail_dfm():   - convert DGBMSF() to DBGTRC()   - simplify coding   - return ok == true iff a formated string is returned - init_dyn_feature_codes():   - remove dyn_format_table_feature_detail_dfm()
0b2aed6d vcp_feature_codes.c: - format_feature_details_display_controller_type():   - better handle the case where the value supplied is not in the lookup table   - compose a message with "Unrecognized" as the SL interpretation   - return true, so the string is not discarded   - add tracing
be795eb1 .gitignore: more to ignore
e7d32e2b api_feature_access.c: - ddca_format_any_vcp_value():   - convert DBGMSF() calls to DBGTRC(), so tracking can be activated on command line
fed4e2e8 Makefile.am: - switch back to using ${libdir} instead of ${datadir} - the ddcutil.pc file is in fact not architecture agnositic - delete comments that are wrong/no longer apply
```

I suggest the standard commit message format:

```text
Concise title about what the fix does

Optional detailed description about why the fix is needed, implementation details, etc. Separated from the title by an empty line.
```

Note that `git log --name-only` shows which files were changed in each commit, so there's no reason to mention that in the commit message, especially not on the first line.

If you get a PR that's not quite right, you can usually push a commit that fixes it straight to the PR branch and then merge. (I say "usually" because the PR author may not always have allowed authors to push changes to the PR branch, but often they will have.)

**Comment by rockowitz** [comment]
Thank you for your suggestions.  I'll give them consideration, 
especially the suggestion of a summary line.

I appreciate that the log file format is non-standard.  If there were 
other contributors (there have been 4 PRs total) I would feel a greater 
need to use a more standard format.   But the fact is that there aren't 
and the current format works for me.  Yes, --name-only shows the names 
of the files changed, but describing the changes on a per file/function 
basis makes it easy for me to grasp what important has changed without 
poking around in detailed diffs.

Regards,
Sanford

**Pull request closed without merging**
