### PR TITLE
Fix CRLF problem in main.c.

### PR DESCRIPTION
**Pull request by sorenstoutner**
src/app_ddcutil/main.c currently has Windows CRLF (Carriage Return, Line Feed) line endings.  This pull request simply changes them to Linux LF (Line Feed).

This is a helpful change for Debian packaging using gbp (git-buildpackage) as otherwise the version in Git and the version in the tarball are not the same, leading to an error message.

(FYI, the current Debian gbp packaging can be seen at https://salsa.debian.org/debian/ddcutil.)

### CODE REVIEW

**Comment by rockowitz** [comment]
Thank you.  No idea how this happened but I'll take care in the future to keep CRLF line endings out of the source.

**Comment by sorenstoutner** [comment]
No problem.  I have actually found this to be a relatively common problem in upstream source code, especially on older files if development sometimes happened on Windows system.

**Comment by JL2210** [comment]
You didn't just change line endings in this PR. Build fails now.

**Comment by sorenstoutner** [comment]
Which changes do you see besides the line endings?

**Comment by JL2210** [comment]
```
14d13
< #include <base/drm_connector_state.h>
40d38
< #include "util/regex_util.h"
94d91
< #include "ddc/ddc_save_current_settings.h"
363,366c360
<    Error_Info * submaster_errs = submaster_initializer(parsed_cmd);  // shared with libddcutil
<    if (submaster_errs) {
<       errinfo_report_details(submaster_errs, 0);
<       ERRINFO_FREE(submaster_errs);
---
>    if (!submaster_initializer(parsed_cmd))    // shared with libddcutil
368d361
<    }
577,578c570,571
<          if (app_check_dynamic_features(dh->dref)) {
<             ensure_vcp_version_set(dh);
---
>          app_check_dynamic_features(dh->dref);
>          ensure_vcp_version_set(dh);
580,584c573,574
<             DDCA_Status ddcrc = app_capabilities(dh);
<             main_rc = (ddcrc==0) ? EXIT_SUCCESS : EXIT_FAILURE;
<          }
<          else
<             main_rc = EXIT_FAILURE;
---
>          DDCA_Status ddcrc = app_capabilities(dh);
>          main_rc = (ddcrc==0) ? EXIT_SUCCESS : EXIT_FAILURE;
591,592c581,582
<          if (app_check_dynamic_features(dh->dref)) {
<             ensure_vcp_version_set(dh);
---
>          app_check_dynamic_features(dh->dref);
>          ensure_vcp_version_set(dh);
594,598c584,585
<             Public_Status_Code psc = app_show_feature_set_values_by_dh(dh, parsed_cmd);
<             main_rc = (psc==0) ? EXIT_SUCCESS : EXIT_FAILURE;
<          }
<          else
<             main_rc = EXIT_FAILURE;
---
>          Public_Status_Code psc = app_show_feature_set_values_by_dh(dh, parsed_cmd);
>          main_rc = (psc==0) ? EXIT_SUCCESS : EXIT_FAILURE;
605,606c592,593
<          if (app_check_dynamic_features(dh->dref)) {
<             ensure_vcp_version_set(dh);
---
>          app_check_dynamic_features(dh->dref);
>          ensure_vcp_version_set(dh);
608,612c595,596
<             int rc = app_setvcp(parsed_cmd, dh);
<             main_rc = (rc == 0) ? EXIT_SUCCESS : EXIT_FAILURE;
<          }
<          else
<             main_rc = EXIT_FAILURE;
---
>          int rc = app_setvcp(parsed_cmd, dh);
>          main_rc = (rc == 0) ? EXIT_SUCCESS : EXIT_FAILURE;
645,646c629,630
<          if (app_check_dynamic_features(dh->dref)) {
<             ensure_vcp_version_set(dh);
---
>          app_check_dynamic_features(dh->dref);
>          ensure_vcp_version_set(dh);
648c632
<             Public_Status_Code psc =
---
>          Public_Status_Code psc =
652,655c636
<             main_rc = (psc==0) ? EXIT_SUCCESS : EXIT_FAILURE;
<          }
<          else
<             main_rc = EXIT_FAILURE;
---
>          main_rc = (psc==0) ? EXIT_SUCCESS : EXIT_FAILURE;
660d640
<    {
662,663c642,643
<       if (app_check_dynamic_features(dh->dref)) {
<          ensure_vcp_version_set(dh);
---
>       app_check_dynamic_features(dh->dref);
>       ensure_vcp_version_set(dh);
665,669c645,646
<          app_read_changes_forever(dh, parsed_cmd->flags & CMD_FLAG_X52_NO_FIFO);     // only returns if fatal error
<          main_rc = EXIT_FAILURE;
<       }
<       else
<          main_rc = EXIT_FAILURE;
---
>       app_read_changes_forever(dh, parsed_cmd->flags & CMD_FLAG_X52_NO_FIFO);     // only returns if fatal error
>       main_rc = EXIT_FAILURE;
671d647
<    }
674d649
<    {
676,677c651,652
<       if (app_check_dynamic_features(dh->dref)) {
<          ensure_vcp_version_set(dh);
---
>       app_check_dynamic_features(dh->dref);
>       ensure_vcp_version_set(dh);
679,683c654,655
<          app_probe_display_by_dh(dh);
<          main_rc = EXIT_SUCCESS;
<       }
<       else
<          main_rc = EXIT_FAILURE;
---
>       app_probe_display_by_dh(dh);
>       main_rc = EXIT_SUCCESS;
685d656
<    }
926,931d896
< 
<    if (parsed_cmd->cmd_id == CMDID_NOOP) {
<       rpt_vstring(0, "Executing options only");
<       rpt_nl();
<    }
< 
933a899
> 
936c902
<    if (parsed_cmd->flags2 & CMD_FLAG2_F2) {
---
>    if (parsed_cmd->flags & CMD_FLAG_F2) {
938,939d903
<       if (use_drm_connector_states)
<          report_drm_connector_states(0);
975,979d938
<    else if (parsed_cmd->cmd_id == CMDID_NOOP) {
<       // rpt_vstring(0, "Executing options only");   // already reported
<       main_rc = EXIT_SUCCESS;
<    }
< 
981c940
<       DBGMSG("Executing temporarily defined command C1: watch for display connection/disconnection");
---
>       DBGMSG("Executing temporarily defined command C1");
988c947,952
<          Error_Info * erec = ddc_start_watch_displays(DDCA_EVENT_CLASS_DISPLAY_CONNECTION);
---
>          DDCA_Display_Event_Class event_classes = DDCA_EVENT_CLASS_ALL;
>          if (parsed_cmd->flags&CMD_FLAG_F13)
>             event_classes = DDCA_EVENT_CLASS_DISPLAY_CONNECTION;
>          if (parsed_cmd->flags&CMD_FLAG_F14)
>             event_classes = DDCA_EVENT_CLASS_DPMS;
>          Error_Info * erec = ddc_start_watch_displays(event_classes);
989a954
>             DBGMSG(erec->detail);
994c959
<             DBGMSG("Watching for 60 minutes");
---
>             DBGMSG("Sleeping for 60 minutes");
996,997d960
<             DBGMSG("Terminating execution after 60 minutes");
<             ddc_stop_watch_displays(true, NULL);
1005d967
<       // report_drm_connector_states(0);
1028c990
<       if ( parsed_cmd->flags2 & CMD_FLAG2_F4) {
---
>       if ( parsed_cmd->flags & CMD_FLAG_F4) {
1051,1052d1012
<       if (parsed_cmd->output_level >= DDCA_OL_VERBOSE)
<          force_envcmd_settings(parsed_cmd);
1074c1034
<       bool is_monitor = (parsed_cmd->flags&CMD_FLAG_ENABLE_USB) && check_usb_monitor( parsed_cmd->args[0] );
---
>       bool is_monitor = check_usb_monitor( parsed_cmd->args[0] );
```

**Comment by sorenstoutner** [comment]
I submitted the fixed version with the line endings from the Debian update prepared by [rockowitz](https://github.com/rockowitz) that he submitted to the Debian package (can be seen at):

https://salsa.debian.org/debian/ddcutil/-/blob/master/src/app_ddcutil/main.c?ref_type=heads

It didn't look like there had been any changes to main.c in the previous four years, but if your file was somehow different that what was distributed and packaged for Debian it would cause issues.

**Comment by JL2210** [comment]
The branches on this repo are nonstandard, the main one changes every release
Looks like your copy of the file was from around v2.1.2:
```
[james@WileECoyote ~/git/ddcutil]$ git checkout v2.1.2
Previous HEAD position was 3e265eea ddca_ddcutil_version(): disable debug msg
HEAD is now at 90e67d7c change version to 2.1.2, misc cleanup
[james@WileECoyote ~/git/ddcutil]$ dos2unix src/app_ddcutil/main.c 
dos2unix: converting file src/app_ddcutil/main.c to Unix format...
[james@WileECoyote ~/git/ddcutil]$ diff src/app_ddcutil/main.c ../main-new.c 
6c6
< // Copyright (C) 2014-2023 Sanford Rockowitz <rockowitz@minsoft.com>
---
> // Copyright (C) 2014-2024 Sanford Rockowitz <rockowitz@minsoft.com>
184a185
>     report_build_options(depth);
```

**Comment by sorenstoutner** [comment]
All I can say is that this is the copy that https://github.com/rockowitz/ddcutil/pull/447#issuecomment-2327767934 submitted to Debian as part of the 2.1.4 update.  https://github.com/rockowitz/ddcutil/pull/447#issuecomment-2327767934, can you confirm that the files you submitted were actually 2.1.4?

**Comment by JL2210** [comment]
Your pull went to the 2.1.5-dev branch, not 2.1.4. I'm building 2.1.5-dev

**Comment by rockowitz** [comment]
I'm not clear what the problem is.  Here's what I see:

On my system, origin is github

git diff 2.1.4-release...origin/2.1.4-release  shows differences
git diff master...origin/master shows no differences
git diff 2.1.5-dev...origin/2.1.5-dev shows no differences

git diff 2.1.4-release...master shows no differences

File src/app_ddcutil/main.c on 2.1.5-dev is as expected. 

The salsa copy of main.c is identical to that in branch 2.1.4-release, except that the line endings in main.c have changed.

Soren's CFLF patch was against branch 2.1.5-dev on github.  I pulled this patch to my branch, then merged it with the local copy of 2.1.5-dev.  To minimize the number of differences, I first changed the CRLF line endings in main.c to LF.

As @JL2210  notes, the branches on this repo do not follow the general convention that master is the working branch.  Instead, master matches the most recent release, in this case 2.1.4-dev.  The branches were set up years ago, before I appreciated how they are usually set up.  I think that changing to the standard convention would introduce more confusion than it alleviates, so I have left the branch structure as is.  However, I am open to the argument that such a change would be worthwhile.

**Comment by sorenstoutner** [comment]
I apologize if I accidentally submitted the pull request against the wrong branch and made things more complicated than they needed to be.

**Comment by JL2210** [comment]
Ah okay, it builds fine for me now. Seems you had some local changes that weren't properly pushed here.

**Pull request merged**
