### PR TITLE
Fixing minor typo

### PR DESCRIPTION
**Pull request by GoodMirek**
Btw could ddcutil somehow load the i2c-dev module by itself?

### CODE REVIEW

**Comment by rockowitz** [comment]
Mirek,

The primary reason ddcutil doesn't load module i2c-dev is privilege - 
loading modules is a kernel operation.  It can be invoked using the 
syscall() API, or the shell insmod and modprobe commands, but these 
require root privileges.  See, for example, the discussion at 
https://stackoverflow.com/questions/5947286/how-can-linux-kernel-modules-be-loaded-from-c-code. 


Thanks for catching the typo.  It's a never-ending cleanup - kind of 
like sweeping sand on the beach.

Sanford

**Comment by GoodMirek** [comment]
Sanford,

I very much appreciate all your work and I am happy I have been able to help with that smallest one char contribution :)
ddcutil is a big help for me, as my monitor has brightness settings stupidly buried deep deep in OSD.
I run ddcutil with sudo, so for me the option to load i2c-dev module via the ddcutil would be good help.

Mirek

**Comment by rockowitz** [comment]
Mirek,

I'm hesitant about coding ddcutil to behave specially when run as 
root.   All you need to do is add a 1 line file (by convention named 
ddcutil.conf)  to directory /etc/modules-load.d containing the line:
   i2c-dev

That said, the installation scripts in the rpm or dpkg could do the 
above.   Depending on platform, package i2c-tools may
already force loading of i2c-dev in this way.    Actually implementing 
this ability would have to be coordinated with the packagers of ddcutil 
and i2c-tools on each platform.  It's conceivable the group permissions 
could be set in this way as well.  But ddcutil itself shouldn't be 
running around changing the user's execution environment.

Sanford

**Comment by GoodMirek** [comment]
Thanks for explanation.

**Comment by d-vogel** [comment]
Hey @GoodMirek, also convinient is to setup udev rule in order not to have to chmod or run ddcutil as root. I described it in [QMLddcutil](https://github.com/d-vogel/QMLddcutil/blob/master/README.md).

**Pull request closed without merging**
